GET http://localhost:3008/api/greetings

###
GET https://sqlite-greet.onrender.com/api/greetings

###
POST http://localhost:3008/api/greetings
Content-Type: application/json

{
    "language" : "Afrikaans",
    "greeting" : "Goeie dag"
}

###
POST https://sqlite-greet.onrender.com/api/greetings
Content-Type: application/json

{
    "language" : "Afrikaans",
    "greeting" : "Goeie dag"
}
